In [4]:
A = [-1.5 3 2;
     1 -1 0]

B = [-1 -1;
     0 -2;
     1 0]

A * B

C = A*B

2×2 Matrix{Float64}:
  3.5  -4.5
 -1.0   1.0

# Gram matrix

Gram matrix of matrix A is $ G = A^TA $

- A^TA is symmetric
- the (i,j) element: $ (A^TA)_{ij} $ is the dot product of columns $i$ and $j$ of $ A $
  
\begin{align}
    (A^TA)_{ij} = A_i^TA_j
\end{align}

In [12]:
A = randn(10, 3)

10×3 Matrix{Float64}:
 -0.0875341    -0.96744   -0.693594
 -1.03982      -0.610822  -0.53691
 -1.57232       0.671983  -0.541305
 -0.767178      0.697486  -0.74712
 -0.620496     -0.439172   0.851933
 -1.76164      -2.23999   -0.579075
 -0.113357      0.785229   0.421156
  0.523276     -0.459375   0.259775
  0.623041      0.591101   1.61764
  0.000424787   0.449586  -0.661391

In [18]:
using LinearAlgebra
using VMLS
G = A'*A

3×3 Matrix{Float64}:
 8.31289  3.3858   3.63055
 3.3858   8.83667  1.9073
 3.63055  1.9073   5.98071

In [35]:
# G[i, i] is the inner product of column i with itself
lhs = G[2, 2]

rhs1 = A[:, 2]'*A[:, 2]
rhs2 = norm(A[:, 2])^2

println((lhs, rhs1, rhs2))
norm(lhs - rhs1)

(8.836665689764988, 8.836665689764988, 8.83666568976499)


0.0

In [37]:
# G[i, j] is the dot product of column i with column j

lhs = G[1, 2]
rhs = A[:, 1]'*A[:, 2]
println((lhs, rhs))

(3.385799459899099, 3.3857994598990993)


# Composition of linear functions

\begin{align}   
    \Delta(x) = D_{n-1}(D_n(x))
\end{align}

In [40]:
# The diffence matrix Dn
D(n) = [-eye(n-1) zeros(n-1)] + [zeros(n-1) eye(n-1)]

D (generic function with 1 method)

In [39]:
D(5)

4×5 Matrix{Float64}:
 -1.0   1.0   0.0   0.0  0.0
  0.0  -1.0   1.0   0.0  0.0
  0.0   0.0  -1.0   1.0  0.0
  0.0   0.0   0.0  -1.0  1.0

In [42]:
Dn(x) = D(length(x))*x

Dn (generic function with 1 method)

In [43]:
Dn([1, 3, 6, 10, 15])

4-element Vector{Float64}:
 2.0
 3.0
 4.0
 5.0

In [49]:
function delta(x)
    n = length(x)
    Dn = D(n)
    Dn_1 = D(n-1)
    deltamtx = Dn_1*Dn
    return deltamtx *x
end

delta (generic function with 1 method)

In [50]:
x = [1; 3; 6; 10; 15]

Dn(Dn(x))

3-element Vector{Float64}:
 1.0
 1.0
 1.0

In [51]:
delta(x)

3-element Vector{Float64}:
 1.0
 1.0
 1.0